
#ifndef _TMR1_CONFIG_H_
#define _TMR1_CONFIG_H_

/*
1. NORMAL_MODE
2. PWM_PHASE_CORRECT_8BIT
3. PWM_PHASE_CORRECT_9BIT
4. PWM_PHASE_CORRECT_10BIT
5. CTC_MODE_COMP
6. FAST_PWM_8BIT
7. FAST_PWM_9BIT
8. FAST_PWM_10BIT
9. PWM_PHASE_FREQ_CORRECT_ICR
10. PWM_PHASE_FREQ_CORRECT_CMP
11. PWM_PHASE_CORRECT_MODE_ICR
12. PWM_PHASE_CORRECT_MODE_CMP
13. CTC_MODE_ICR
14. FAST_PWM_MODE_ICR
15. FAST_PWM_MODE_CMP
*/
#define NORMAL_MODE




#endif 